export const FETCH_WHEATHER_POSITION = "FETCH_WHEATHER_POSITION";
export const FETCH_GET_CURRENT_POSITION = "FETCH_GET_CURRENT_POSITION";
export const FETCH_NAME_POSITION = "FETCH_NAME_POSITION";
export const LOADING_LOCATION = "LOADING_LOCATION";
export const GET_LOCATION = "GET_LOCATION";
export const CHANGE_CLASS = "CHANGE_CLASS";
